name: Deploy Frontend

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo Code
      uses: actions/checkout@v2
    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '2.x'
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    - name: fix ssl
      run: export NODE_OPTIONS=--openssl-legacy-provider
  
    - name: Setup environment
      run: |
        echo REACT_APP_PRIVATE_MAPBOX_ACCESS_TOKEN=${{ secrets.PRIVATE_MAPBOX_ACCESS_TOKEN }} > .env

    - name: Install Packages
      run: npm install

    - name: Build project
      run: npm run build
